[package]
name = "destruction-studios/net-framework"
version = "0.0.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Symbol = "sleitnick/symbol@2.0.1"
# Signal = "sleitnick/signal@2.0.3"
# Trove = "sleitnick/trove@1.5.0"
# t = "osyrisrblx/t@3.1.1"