[package]
name = "destruction-studios/net"
version = "1.1.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
UniqueKey = "destruction-studios/uniquekey@1.0.4"
Signal = "sleitnick/signal@2.0.3"
# Trove = "sleitnick/trove@1.5.0"
# t = "osyrisrblx/t@3.1.1"